nba_game_predictor/__init__.py
'''
NBA Game Predictor application
'''

from flask import Flask

def create_app():
    '''
    Create Flask app instance
    '''
    app = Flask(__name__)

    from .views import main
    app.register_blueprint(main)

    return app

nba_game_predictor/views.py
from flask import Blueprint, redirect, render_template, request
from .calculations import calc_fourfactors, predict_winner


main = Blueprint('main', __name__)


@main.route('/')
def index():
    return redirect('/predict')


@main.route('/predict')
def predict():
    return render_template('predict.html')


@main.route('/', methods=['POST'])
@main.route('/predict', methods=['POST'])
def upload_and_predict():

    box = {
        "h_fgm": int(request.form.get("h_fgm")),
        "h_fga": int(request.form.get("h_fga")),
        "h_3pm": int(request.form.get("h_3pm")),
        "h_ftm": int(request.form.get("h_ftm")),
        "h_fta": int(request.form.get("h_fta")),
        "h_trb": int(request.form.get("h_trb")),
        "h_orb": int(request.form.get("h_orb")),
        "h_tov": int(request.form.get("h_tov")),
        "a_fgm": int(request.form.get("a_fgm")),
        "a_fga": int(request.form.get("a_fga")),
        "a_3pm": int(request.form.get("a_3pm")),
        "a_ftm": int(request.form.get("a_ftm")),
        "a_fta": int(request.form.get("a_fta")),
        "a_trb": int(request.form.get("a_trb")),
        "a_orb": int(request.form.get("a_orb")),
        "a_tov": int(request.form.get("a_tov")),
        }
    matrix = calc_fourfactors(box)

    winner, proba = predict_winner(matrix)
    return render_template('predict.html', predicted=winner, proba=proba)


@main.route('/about')
def about():
    return render_template('about.html')


@main.route('/fourfactors_predict')
def ff_predict():
    matrix = {
            'h_efg': float(request.form.get('h_efg')),
            'h_tov': float(request.form.get('h_tov')),
            'h_drp': float(request.form.get('h_drp')),
            'h_ftr': float(request.form.get('h_ftr')),
            'a_efg': float(request.form.get('a_efg')),
            'a_tov': float(request.form.get('a_tov')),
            'a_drp': float(request.form.get('a_drp')),
            'a_ftr': float(request.form.get('a_ftr'))
        }
    winner, proba = predict_winner(matrix)
    return render_template('predict.html', predicted=winner, proba=proba)

nba_game_predictor/templates/about.html
{% extends 'base.html' %}

{% block title %}Basketball Game Predictor | About{% endblock %}

{% block css %}{% endblock %}

{% block body %}

<p class="section about desc">
    At the end of the day, basketball may be 'about getting buckets', but there is a lot more that goes
    on within the game that has significant impact on which team ends up getting those buckets. What Dean Oliver coined
    as the 'Four Factors' summerizes the most important parts of the game captured by the traditional box score. Each of
    these four composite statistics can be calculated for each team to directly compare how each team fared using
    percentages or rates.
</p>

<div class="section about">

    <h2>The Four Factors</h2>

    <p>
        <b>Effective Field Goal Percentage (EFG%)</b><br />
        Formula: EFG% = (FieldGoalsMade + 0.5 * 3ptFieldGoalsMade) / FieldGoalsAttempted<br />
        Purpose: EFG% gives a measure of how efficently a team is scoring relative to their field goal attempts. Three
        point field goals are given extra weight because of the additional point they provide when made.
    </p>

    <p>
        <b>Turnover Percentage (TOV%)</b><br />
        Formula: TOV% = Turnovers / (FieldGoalsAttempted + 0.44 * FreeThrowsAttempted + Turnovers)<br />
        Purpose: TOV% is the percentage of total possesions that ended in a turnover.
    </p>

    <p>
        <b>Defensive Rebounding Percentage (DRB%)</b><br />
        Formula: DRB% = DefensiveRebounds / (OpponentOffensiveRebounds + DefensiveRebounds)<br />
        Purpose: DRB% is the percentage of available rebounds that a team claimed while on defense. This measure is
        sometimes measured as Offensive RB%, which is the same measure but from the opposite perspective.
    </p>

    <p>
        <b>Free Throw Rate (FTR).</b><br />
        Formula: FTR = FreeThrowsMade / FieldGoalAttempts<br />
        Purpose: FTR is a measure of how often a team gets to the foul line. It is traditionally measured as
        FreeThrowsMade / FieldGoalAttempts or as FreeThrowAttempts / FieldGoalAttempts.
    </p>

    <p>
        For detailed information on these metrics, see Dean Oliver's "Basketball on Paper".
    </p>

    <h2>Conclusions</h2>

    <p>
        While all essential to winning basketball games, not all four metrics are weighted evenly. When examining
        feature and permutation importances in the models, I came to the same approximate weights that Dean Oliver
        found, with the slight exception of Rebounding being weighted slightly less and Shooting slightly more.
    <ol>
        <li>Shooting (40%)</li>
        <li>Turnovers (25%)</li>
        <li>Rebounding (20%)</li>
        <li>Free Throws (15%)</li>
    </ol>
    </p>

    <p>
        Home court advantage does not seem to be an independently relevant factor in the regular season games used for
        modeling. It is possible that homecourt advantage shows in the improvement of other metics such as shooting or
        free throw rate. Further examination of this question is beyond the scope of this project, and would make an
        interestingß topic for future study.
    </p>
</div>

<div class="section about">
    <h2>The Model</h2>

    <p>
        This prediction app uses a tuned LogisticRegression model from the SciKit-Learn library.
    </p>

    <p>
        Consideration was given to several types of classification models:

        <ul>
            <li>LogisticRegression (sklearn lib)</li>
            <li>RidgeClassifier (sklearn lib)</li>
            <li>RandomForestClassifier (sklearn lib)</li>
            <li>XGBClassifier (XGBoost lib)</li>
        </ul>

        The LogisticRegression model had the highest base accuracy score of all models considered, and was selected
        for further tuning.
    </p>
</div>
{% endblock %}

nba_game_predictor/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>

    <!-- CSS files -->
    <link rel="stylesheet" href="static/styles.css">
    {% block css %}{% endblock %}
</head>

<body>
    <div class="container theme-showcase">
        <div class="header">
            <h1>Basketball Game Predictor</h1>
            <ul class="navigation">
                <li><a type="button" href="{{ url_for('main.predict') }}">Predict</a></li>
                <li><a type="button" href="{{ url_for('main.about') }}">How it works</a></li>
            </ul>
        </div>

        {% block body %}{% endblock %}
    </div>
</body>

</html>

nba_game_predictor/templates/predict.html
{% extends 'base.html' %}

{% block title %}Basketball Game Predictor{% endblock %}

{% block css %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

{% block body %}
<p class="desc">
    Input the boxscore data from a basketball game and hit the button to predict the winner!
</p>
<div class="ingest section">
    <div class="title">Boxscore Input</div>
    <form id="boxscore" action="" method="post">
        <table>
            <tr>
                <th>Team</th>
                <th>FGM</th>
                <th>FGA</th>
                <th>3PM</th>
                <th>FTM</th>
                <th>FTA</th>
                <th>TRB</th>
                <th>ORB</th>
                <th>TOV</th>
            </tr>
            <tr>
                <th>Home</th>
                <td><input type="number" step="any" min="0" required="true" id="h_fgm" name="h_fgm"></td>
                <td><input type="number" step="any" min="0" required="true" id="h_fga" name="h_fga"></td>
                <td><input type="number" step="any" min="0" required="true" id="h_3pm" name="h_3pm"></td>
                <td><input type="number" step="any" min="0" required="true" id="h_ftm" name="h_ftm"></td>
                <td><input type="number" step="any" min="0" required="true" id="h_fta" name="h_fta"></td>
                <td><input type="number" step="any" min="0" required="true" id="h_trb" name="h_trb"></td>
                <td><input type="number" step="any" min="0" required="true" id="h_orb" name="h_orb"></td>
                <td><input type="number" step="any" min="0" required="true" id="h_tov" name="h_tov"></td>
            </tr>
            <tr>
                <th>Away</th>
                <td><input type="number" step="any" min="0" required="true" id="a_fgm" name="a_fgm"></td>
                <td><input type="number" step="any" min="0" required="true" id="a_fga" name="a_fga"></td>
                <td><input type="number" step="any" min="0" required="true" id="a_3pm" name="a_3pm"></td>
                <td><input type="number" step="any" min="0" required="true" id="a_ftm" name="a_ftm"></td>
                <td><input type="number" step="any" min="0" required="true" id="a_fta" name="a_fta"></td>
                <td><input type="number" step="any" min="0" required="true" id="a_trb" name="a_trb"></td>
                <td><input type="number" step="any" min="0" required="true" id="a_orb" name="a_orb"></td>
                <td><input type="number" step="any" min="0" required="true" id="a_tov" name="a_tov"></td>
            </tr>
        </table>
    </form>
</div>

<button type="submit" form="boxscore">Predict</button>

<div class="output section">
    <div class="title">Prediction</div>
    <table>
        <tr>
            <td>Predicted Winner:</td>
            <td>{% if predicted %}{{ predicted }}{% endif %}</td>
        </tr>
        <tr>
            <td>Probability:</td>
            <td>{% if predicted %}{{ proba }}{% endif %}</td>
        </tr>
    </table>

</div>

{% endblock %}

nba_game_predictor/templates/predict_fourfactors.html
{% extends 'base.html' %}

{% block title %}Basketball Game Predictor{% endblock %}

{% block css %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock %}

{% block body %}
<div>
    Brief description...

</div>
<div class="ingest">

    <form id="fourfactors" method="post">
        <span class="form_desc">Enter the four factors data as decimals here:<br />
            <i>For example: Home EFG% as 0.55</i>
        </span>
        <table>
            <tr>
                <th>Team</th>
                <th>EFG%</th>
                <th>TOV Rate</th>
                <th>DRB Rate</th>
                <th>FTR</th>
            </tr>
            <tr>
                <th>Home</th>
                <td><input type="number" step="any" min="0" required="true" id="h_efg" name="h_efg"></td>
                <td><input type="number" step="any" min="0" required="true" id="h_tov" name="h_tov"></td>
                <td><input type="number" step="any" min="0" required="true" id="h_drp" name="h_drp"></td>
                <td><input type="number" step="any" min="0" required="true" id="h_ftr" name="h_ftr"></td>
            </tr>
            <tr>
                <th>Away</th>
                <td><input type="number" step="any" min="0" required="true" id="a_efg" name="a_efg"></td>
                <td><input type="number" step="any" min="0" required="true" id="a_tov" name="a_tov"></td>
                <td><input type="number" step="any" min="0" required="true" id="a_drp" name="a_drp"></td>
                <td><input type="number" step="any" min="0" required="true" id="a_ftr" name="a_ftr"></td>
            </tr>
        </table>
        <input type="hidden" name="fourfactors">
        <button type="submit">Predict</button>
    </form>

</div>

<div class="output">
    {% if predicted %}
    Predicted Winner: {{ predicted }}
    <br />
    Probability: {{ proba }}
    {% endif %}
</div>

{% endblock %}